# TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}
# You'll want to modify most of this file with your own branding and links.

title: "We invite You to enter Our Beautiful Gate" # Appears after the title Page eg. Title - Web Starter
subtitle: "to meet God's Fragile Butterflies, the Niños of Puerta Hermosa."
description: "Fourteen years ago when we rescued two very sick little girls, God called upon our hearts ❤ to open Beautiful Gate Orphanage. That dream is now a fully functional orphanage dedicated to abandoned special-needs children, whom we call Fragile Butterflies 🦋. We deeply love ❤ them and they bless us abundantly."
url: "http://enter.giof.org/"
author: "GIOF"
meta_data:
  twitter: "@"
  default_social_image: "/static/logo.png"

# Careful! Use quotes around your links.
navigation:
  - name: Welcome
    url: "#welcome"
    description: Return to the top
  - name: DONATE
    url: "#products"
    description: Help support us
  - name: Contact
    url: "http://giof.org/contact-us/"
    description:
  - name: Support Us
    url: "http://giof.org/support_giof/"
    description:

# The following are the headings for the navigation
texts:
  highlightsTitle: "Watch our 2020 Videos!"
  highlightsText: "Click the links below to load up videos showing what we've been doing."
  aboutTitle: "$30,000 matching grant"
  productsTitle: "Donation Items"

currency_symbol: $

# Careful! Use quotes around your links.
social_networks:
  blog:
    url: "http://giof.org/"
    icon: "fas fa-blog-square"
  email:
    url: "http://giof.org/contact-us/"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/GenesisDiez/"
    icon: "fab fa-facebook-square"
  youtube:
    url: "https://www.youtube.com/channel/UCPYuKWST08z9LoMvflR_AIw"
    icon: "fab fa-youtube"
