# TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}
# You'll want to modify most of this file with your own branding and links.

title: "“Healing Wounded Hearts” Premier Invitation!!" # Appears after the title Page eg. Title - Web Starter
subtitle: >
  SAVE THE DATE! <br>
  MAY 20th Friday at 7pm PST
description: "Fourteen years ago when we rescued two very sick little girls, God called upon our hearts ❤ to open Beautiful Gate Orphanage. That dream is now a fully functional orphanage dedicated to abandoned special-needs children, whom we call Fragile Butterflies 🦋. We deeply love ❤ them and they bless us abundantly."
url: "http://enter.giof.org/"
author: "GIOF"
meta_data:
  twitter: "@foxycart" # Used in the meta tags
  default_social_image: "/static/logo.png"

# Careful! Use quotes around your links.
# You can add additional nav items, and the urls can be external links.
navigation:
  - name: Home
    url: "https://genesisdiez.org/"
    description: Return to the home page
  - name: DONATE
    url: "#donate"
    description: Help support us
  - name: Needed Items
    url: "#products"
    description: Help support us
  - name: Contact
    url: "https://genesisdiez.org/contact-us/"
    description:

# The following are the headings for the navigation
texts:
  highlightsTitle: "Watch our 2020 Videos!"
  highlightsText: "Click the links below to load up videos showing what we've been doing."
  aboutTitle: ""
  donateTitle: "Support Us"
  productsTitle: "Help Us with Needed Supplies"

currency_symbol: $

# Careful! Use quotes around your links.
social_networks:
  blog:
    url: "http://giof.org/"
    icon: "fas fa-blog-square"
  email:
    url: "http://giof.org/contact-us/"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/GenesisDiez/"
    icon: "fab fa-facebook-square"
  youtube:
    url: "https://www.youtube.com/channel/UCPYuKWST08z9LoMvflR_AIw"
    icon: "fab fa-youtube"

livestream: dMOmg6enrU8
livestreamDomain: donate.genesisdiez.org
